var product1=[{
    "id" : "1",
    "title" : "Amazon Aurora",
    "description" : "Amazon Aurora (Aurora) is a fully managed relational database engine that's compatible with MySQL and PostgreSQL. You already know how MySQL and PostgreSQL combine the speed and reliability of high-end commercial databases with the simplicity and cost-effectiveness of open-source databases. ",
    "Workflow_requests" : "5",
    "State_transitions_per_workflow" : "Approx_Avg(10)",
    "Estimate_price" : "$ 139",
},{
    "id" : "2",
    "title" : "Redshift",
    "description" : "Amazon Redshift is a data warehouse product which forms part of the larger cloud-computing platform Amazon Web Services. It is built on top of technology from the massive parallel processing data warehouse company ParAccel, to handle large scale data sets and database migrations",
    "Workflow_requests" : "10",
    "State_transitions_per_workflow" : "Approx_Avg(20)",   
    "Estimate_price" : "$ 145",
},{
    "id" : "3",
    "title" : "Dynamo DB",
    "description" : "Amazon DynamoDB is a fully managed proprietary NoSQL database service that supports key–value and document data structures and is offered by Amazon.com as part of the Amazon Web Services portfolio. DynamoDB exposes a similar data model to and derives its name from Dynamo, but has a different underlying implementation",
    "Workflow_requests" : "15",
    "State_transitions_per_workflow" : "Approx_Avg(30)",   
    "Estimate_price" : "$ 149",
}]
var product2=[{
    "id" : "1",
    "title" : "NOSQL",
    "description" : "NoSQL databases are databases based on data models other than relational tables. Types of NoSQL databases include key-value, document, graph, and wide-column. These databases are becoming more popular as organizations create larger volumes and a greater variety of unstructured data",
    "Workflow_requests" : "20",
    "State_transitions_per_workflow" : "Approx_Avg(40)",   
    "Estimate_price" : "$120",
},{
    "id" : "2",
    "title" : "In Memory",
    "description" : "In-Memory OLTP technology provides extremely fast data access operations by keeping all data in memory. It also uses specialized indexes, native compilation of queries, and latch-free data-access to improve performance of the OLTP workload.",
    "Workflow_requests" : "25",
    "State_transitions_per_workflow" : "Approx_Avg(50)",    
    "Estimate_price" : "$ 124",
},{
    "id" : "3",
    "title" : "Relational",
    "description" : "It is a scalable, relational database service built for the cloud and is based on Microsoft SQL Server Database Engine. It is available with three deployment options- Azure SQL Database server, Azure Virtual Network, and Azure SQL Database Serverless.",
    "Workflow_requests" : "30",
    "State_transitions_per_workflow" : "Approx_Avg(60)",    
    "Estimate_price" : "$ 129",
}]
var product3=[{
    "id" : "1",
    "title" : "Cloud SQL",
    "description" : "Cloud SQL is a fully-managed database service that helps you set up, maintain, manage, and administer your relational databases on Google Cloud Platform.",
    "Workflow_requests" : "35",
    "State_transitions_per_workflow" : "Approx_Avg(70)",    
    "Estimate_price" : "$ 132",
},{
    "id" : "2",
    "title" : "Cloud Spanner",
    "description" : "Cloud Spanner is a fully managed, mission-critical, relational database service that offers transactional consistency at global scale, automatic, synchronous replication for high availability, and support for two SQL dialects: Google Standard SQL (ANSI 2011 with extensions) and PostgreSQL",
    "Workflow_requests" : "40",
    "State_transitions_per_workflow" : "Approx_Avg(80)",    
    "Estimate_price" : "$ 123",
},{
    "id" : "3",
    "title" : "Bare Metal Solution",
    "description" : "Google Bare Metal Solution is our bridge to get off the Oracle database entirely. It gives us the flexibility to move the rest of our platform to the cloud so we can now modernize faster.",
    "Workflow_requests" : "45",
    "State_transitions_per_workflow" : "Approx_Avg(90)",
    "Estimate_price" : "$ 136",
}]
var product4=[{
    "id" : "1",
    "title" : "Oracle Autonomous Database",
    "description" : "An autonomous database is a cloud database that uses machine learning to automate database tuning, security, backups, updates, and other routine management tasks traditionally performed by DBAs. Unlike a conventional database, an autonomous database performs all these tasks and more without human intervention.",
    "Workflow_requests" : "50",
    "State_transitions_per_workflow" : "Approx_Avg(100)",   
    "Estimate_price" : "$ 139",
},{
    "id" : "2",
    "title" : "Oracle Exadata Database Service",
    "description" : "The Oracle Exadata Database Machine is a computing platform optimized for running Oracle Databases. Exadata is a combined hardware and software platform that includes scale-out Intel x86-64 compute and storage servers, RoCE or InfiniBand networking, persistent memory, NVMe flash, and specialized software",
    "Workflow_requests" : "60",
    "State_transitions_per_workflow" : "Approx_Avg(120)",    
    "Estimate_price" : "$ 145",
},{
    "id" : "3",
    "title" : "Oracle Base Database Service.",
    "description" : "Oracle Base Database Service enables you to deploy Oracle Enterprise Edition or Oracle Standard Edition 2 databases on single-node DB systems",
    "Workflow_requests" : "65",
    "State_transitions_per_workflow" : "Approx_Avg(130)",    
    "Estimate_price" : "$ 152",
}]