var product1 = [{
    "id": "1",
    "title": "Amazon Aurora",
    "description": "Amazon Aurora MySQL Compatible relational database is built for the cloud, that combines performance and availability of traditional enterprise databases with the simplicity and cost-effectiveness of open source databases.",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "100 per-second",
    "Estimate_price": "Rs. 2500",
}, {
    "id": "2",
    "title": "Redshift",
    "description": "Amazon Redshift is a fully managed, petabyte-scale data warehouse service in the cloud. Amazon Redshift also extends data warehouse queries to your data lake, with no loading required. You can run analytic queries against petabytes of data stored locally in Redshift, and directly against exabytes of data stored in Amazon S3",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 3000",
}, {
    "id": "3",
    "title": "Dynamo DB",
    "description": "Amazon DynamoDB is a key-value and document database that delivers single-digit millisecond performance at any scale. It's a fully managed, multiregion, multimaster, durable database with built-in security, backup and restore, and in-memory caching for internet-scale applications.",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 4000",
}]
var product2 = [{
    "id": "1",
    "title": "Azure Cosmos DB",
    "description": "Azure Cosmos DB is a fully managed, serverless NoSQL database for high-performance applications of any size or scale. Get guaranteed single-digit millisecond performance and 99.999-percent availability, backed by SLAs, automatic and instant scalability, enterprise-grade security, and open-source APIs for NoSQL databases including MongoDB and Cassandra. Enjoy fast writes and reads anywhere in the world with multi-region writes and data replication.",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 2700",
}, {
    "id": "2",
    "title": "In Memory",
    "description": "Azure In Memory Database info here",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 3000",
}, {
    "id": "3",
    "title": "Relational",
    "description": "Azure Relational Database info here",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 4000",
}]
var product3 = [{
    "id": "1",
    "title": "Cloud SQL",
    "description": "Cloud SQL info here",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 2700",
}, {
    "id": "2",
    "title": "Cloud Spanner",
    "description": "Cloud Spanner info here",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 3000",
}, {
    "id": "3",
    "title": "Bare Metal Solution",
    "description": "Bare Metal Solution info here",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 4000",
}]
var product4 = [{
    "id": "1",
    "title": "Oracle Autonomous Database",
    "description": "A fully automated database service that makes it easy for all organizations to develop and deploy application workloads regardless of complexity, scale, or criticality. Autonomous Database’s converged engine supports diverse data types, simplifying application development and deployment from modeling and coding to ETL, database optimization, and data analysis.",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 2700",
}, {
    "id": "2",
    "title": "Oracle Exadata Database Service",
    "description": "Oracle Exadata Database Service is an automated Oracle Database service that allows organizations to run databases with the highest performance, availability, security, and cost effectiveness. Databases run faster and with fewer resources on scale-out Exadata infrastructure that includes unique optimizations for transaction processing, analytics, and mixed workloads.",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 3000",
}, {
    "id": "3",
    "title": "Oracle Database Service.",
    "description": "Oracle Enterprise Database Service is a managed compute and storage platform that allows you to securely run Oracle Database workloads in Oracle Cloud Infrastructure (OCI). Flexible virtual machine shapes and consumption-based pricing simplifies meeting application performance and availability requirements.",
    "Storage": "100 Gb",
    "Base_ioRate": "100 per-second",
    "Peak_ioRate": "120 per-second",
    "Estimate_price": "Rs. 4000",
}]