var product1=[{
    "id" : "1",
    "title" : "S3 Standard ",
    "description" : "S3 Standard is best used for general-purpose storage of frequently accessed data.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 30.05"
},{
    "id" : "2",
    "title" : "S3 Glaceir Insant Retrival",
    "description" : "S3 Glacier Instant Retrieval storage class delivers the lowest cost storage for long-lived data and provides the fastest access to archive storage, with the same throughput and milliseconds access as the S3 Standard and S3 Standard-IA storage classes.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 25.50",
},{
    "id" : "3",
    "title" : "S3 Infrequent Access",
    "description" : "S3 Standard-Infrequent Access is for data that is accessed less frequently, but requires rapid access when needed.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 24.00",
}]
var product2=[{
    "id" : "0",
    "title" : "Blob Storage",
    "description" : "Azure Blob Storage helps you create data lakes for your analytics needs, and provides storage to build powerful cloud-native and mobile apps.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 26.32",
},{
    "id" : "1",
    "title" : "Cool Blob Storage",
    "description" : "Cool Blob Storage is low cost storage for cool object data. Example use cases for cool storage include backups, media content, scientific data, compliance and archival data. In general, any data that is seldom accessed is a perfect candidate for cool storage.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 35.75",
},{
    "id" : "2",
    "title" : "Data Lake Storage Gen2",
    "description" : "Data Lake Storage Gen2 provides file system semantics, file-level security, and scale. Because these capabilities are built on Blob storage, you'll also get low-cost, tiered storage, with high availability/disaster recovery capabilities.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 27.64",
}]
var product3=[{
    "id" : "1",
    "title" : "Google Standard Storage",
    "description" : "Standard Storage is suitable for frequently accessed data (“hot” data) and/or kept only for limited time periods.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 23.40",
},{
    "id" : "2",
    "title" : "Google Archival Storage",
    "description" : "Archive Storage is Google’s lowest-cost storage service for data archiving disaster recovery and online backup. As opposed to the “coldest” storage solution provided by other Cloud suppliers, your data is accessible within milliseconds, rather than hours or days.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$75",
},{
    "id" : "3",
    "title" : "Google Nearline Storage",
    "description" : "Google Cloud Storage Nearline is a public cloud storage service from Google intended for data archiving, backup and disaster recovery. ",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 17",
}]
var product4=[{
    "id" : "1",
    "title" : "Block Volumes",
    "description" : "In block volumes, you can create, attach, connect, and move volumes, as well as change volume performance, as needed, to meet your storage, performance, and application requirements.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "Rs. 2700",
},{
    "id" : "2",
    "title" : "Object Storage-Standard",
    "description" : "Object Storage offers multiple management interfaces that let you easily manage storage at scale. The elasticity of the platform lets you start small and scale seamlessly, without experiencing any degradation in performance or service reliability.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 25.5",
},{
    "id" : "3",
    "title" : "File Storage",
    "description" : "File Storage eliminates the need to provision capacity in advance, so customers pay only for the capacity they need. File Storage also offers snapshot and clone capabilities to simplify business continuity for enterprise applications.",
    "put" : "1000000 per second",
    "get" : "50000 per second",
    "rom" : "1000 Gb",
    "price" : "$ 24.00",
}]